version: '2'
services:

  database:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=development
  memcached:
    image: memcached
  app:
    image: octobox
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - database:database.service.octobox.internal
      - memcached:memcached.service.octobox.internal
    environment:
      - RAILS_ENV=development
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OCTOBOX_DATABASE_NAME=postgres
      - OCTOBOX_DATABASE_USER=postgres
      - OCTOBOX_DATABASE_PASSWORD=development
      - OCTOBOX_DATABASE_HOST=database.service.octobox.internal
      - MEMCACHEDCLOUD_SERVERS=memcached.service.octobox.internal
    command: bin/docker-start
